# imports

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.datasets import fetch_openml
from sklearn.cluster import KMeans

from sklearn.metrics import silhouette_score
from sklearn.metrics import confusion_matrix

import pickle

In [32]:
import matplotlib.pyplot as plt
import seaborn as sns

In [164]:
from sklearn.cluster import DBSCAN

# data

In [2]:
mnist = fetch_openml('mnist_784', version=1, as_frame=True)
mnist.target = mnist.target.astype(np.uint8)

In [3]:
X = mnist["data"]
y = mnist["target"]

# KMeans

In [4]:
n_kmeans = [8, 9, 10, 11, 12]

In [5]:
kmeans_clfs = []
preds = []

for n in range(len(n_kmeans)):
    print(f"n = {n_kmeans[n]}\n")
    clf = KMeans(n_clusters=n_kmeans[n], random_state=42)
    kmeans_clfs.append(clf)
    preds.append(clf.fit_predict(X))

n = 8

n = 9

n = 10

n = 11

n = 12



## silhoutte scores

In [6]:
s_scores = []

In [7]:
for clf in kmeans_clfs:
    s_score = silhouette_score(X, clf.labels_)
    s_scores.append(s_score)

KeyboardInterrupt: 

In [ ]:
s_scores

In [14]:
with open("kmeans_sil.pkl", "wb") as f:
    pickle.dump(s_scores, f, pickle.HIGHEST_PROTOCOL)

## confusion matrix

In [10]:
print(kmeans_clfs[2], preds[2])
confusion_matrix_k10 = confusion_matrix(y, preds[2])
print(confusion_matrix_k10)

KMeans(n_clusters=10, random_state=42) [8 9 3 ... 5 2 6]
[[ 290    2 1265   39    9    7  162    4   72 5053]
 [   8 4293    7    7   10   11    7 3526    8    0]
 [ 323  423  246  216 4863   78  147  436  201   57]
 [4581  449  461  193  216   45   31   58 1083   24]
 [   0  178  288 3728   29 2173  168  234   17    9]
 [2129  155 1812  432    7  215   67  280 1156   60]
 [  38  190 2068   67   53    4 4326   45   14   71]
 [   6  372   12 2094   53 4399    4  314   18   21]
 [1212  335  292  208   53  193   51  330 4115   36]
 [  87  261   31 3462   19 2849   16   95   87   51]]


In [9]:
indices_max = np.argmax(confusion_matrix_k10, axis=1)
indices_max

array([9, 1, 4, 0, 3, 0, 6, 5, 8, 3])

In [11]:
indices_max_set = set(indices_max)
indices_max_set

{0, 1, 3, 4, 5, 6, 8, 9}

In [12]:
with open("kmeans_argmax.pkl", "wb") as f:
    pickle.dump(indices_max_set, f, pickle.HIGHEST_PROTOCOL)

# DBSCAN

In [49]:
distances = set()

In [50]:
for i in range(300):
    for j in range(300):
        distances.add(np.linalg.norm(X.loc[i] - X.loc[j]))

In [70]:
distances_list = list(distances)
distances_list.sort()

In [72]:
dist = []

for i in range(1, 11):
    dist.append(distances_list[i])

In [74]:
with open("dist.pkl", "wb") as f:
    pickle.dump(dist, f, pickle.HIGHEST_PROTOCOL)

In [154]:
eps_list = []

In [162]:
s = sum(dist[7:]) / 3
s_top = s * 1.1
step = s * 0.04

index = 0
while s < s_top:
    eps_list.append(s)
    s += step


In [169]:
dbscans = []

for eps in eps_list:
    print(f"eps = {eps}")
    dbscan = DBSCAN(eps=eps)
    dbscan.fit(X)
    dbscans.append(dbscan)
    print("appended")

eps = 722.1570820655119
appended
eps = 751.0433653481324
appended
eps = 779.9296486307529
appended


In [177]:
dbscan_len_list = []

for dbscan in dbscans:
    dbscan_len_list.append(len(set(dbscan.labels_)))

In [178]:
with open("dbscan_len.pkl", "wb") as f:
    pickle.dump(dbscan_len_list, f, pickle.HIGHEST_PROTOCOL)