# imports

In [24]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.datasets import fetch_openml
from sklearn.cluster import KMeans

from sklearn.metrics import silhouette_score
from sklearn.metrics import confusion_matrix

import pickle

# data

In [2]:
mnist = fetch_openml('mnist_784', version=1, as_frame=True)
mnist.target = mnist.target.astype(np.uint8)

In [3]:
X = mnist["data"]
y = mnist["target"]

## KMeans

In [4]:
n_kmeans = [8, 9, 10, 11, 12]

In [5]:
kmeans_clfs = []
preds = []

for n in range(len(n_kmeans)):
    print(f"n = {n_kmeans[n]}\n")
    clf = KMeans(n_clusters=n_kmeans[n], random_state=42)
    kmeans_clfs.append(clf)
    preds.append(clf.fit_predict(X))

n = 8

n = 9

n = 10

n = 11

n = 12



In [6]:
preds

[array([4, 3, 6, ..., 1, 4, 5], dtype=int32),
 array([1, 0, 7, ..., 3, 1, 5], dtype=int32),
 array([8, 9, 3, ..., 5, 2, 6], dtype=int32),
 array([ 3, 10,  7, ...,  9,  2,  5], dtype=int32),
 array([0, 3, 1, ..., 2, 7, 5], dtype=int32)]

## Silhoutte scores

In [7]:
s_scores = []

In [9]:
for clf in kmeans_clfs:
    s_score = silhouette_score(X, clf.labels_)
    s_scores.append(s_score)

In [10]:
s_scores

[0.07338401965925966,
 0.05683381826333592,
 0.05869201052848778,
 0.05836351154790604,
 0.05894738457992754]

In [14]:
with open("kmeans_sil.pkl", "wb") as f:
    pickle.dump(s_scores, f, pickle.HIGHEST_PROTOCOL)

## confusion matrix

In [26]:
confusion_matrices = []

for pred in preds:
    con = confusion_matrix(y, pred)
    confusion_matrices.append(con)

In [36]:
indices_max = set()

for mat in confusion_matrices:
    print(np.argmax(mat, axis=1))
    # indices_max.add(np.argmax(mat, axis=1))
    
indices_max

[3 0 7 2 6 4 5 1 4 6]
[0 6 8 4 7 1 5 3 1 7]
[9 1 4 0 3 0 6 5 8 3]
[10  1  0  8  7  8  5  9  3  4  0]
[ 4  9  6 11  1 11  7  2  0  8  0  0]


set()